// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi6rn353ZtxtfEuKkroyfnJq1hXv5NsQo',
    appId: '1:965701662111:web:06c97167b87edec13af9aa',
    messagingSenderId: '965701662111',
    projectId: 'draftwing-109f2',
    authDomain: 'draftwing-109f2.firebaseapp.com',
    storageBucket: 'draftwing-109f2.firebasestorage.app',
    measurementId: 'G-B31G5B5M0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0zA_f1qdtONpe58v4RlQKF4yJC02Ku88',
    appId: '1:965701662111:android:89afcabc853a934c3af9aa',
    messagingSenderId: '965701662111',
    projectId: 'draftwing-109f2',
    storageBucket: 'draftwing-109f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEXlugvEDUs_8qGySzEsZGTkFeXsuh2xY',
    appId: '1:965701662111:ios:c124d75e0f8120c43af9aa',
    messagingSenderId: '965701662111',
    projectId: 'draftwing-109f2',
    storageBucket: 'draftwing-109f2.firebasestorage.app',
    iosBundleId: 'com.hmz.draftwing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEXlugvEDUs_8qGySzEsZGTkFeXsuh2xY',
    appId: '1:965701662111:ios:c124d75e0f8120c43af9aa',
    messagingSenderId: '965701662111',
    projectId: 'draftwing-109f2',
    storageBucket: 'draftwing-109f2.firebasestorage.app',
    iosBundleId: 'com.hmz.draftwing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi6rn353ZtxtfEuKkroyfnJq1hXv5NsQo',
    appId: '1:965701662111:web:4356a44ff4053ef43af9aa',
    messagingSenderId: '965701662111',
    projectId: 'draftwing-109f2',
    authDomain: 'draftwing-109f2.firebaseapp.com',
    storageBucket: 'draftwing-109f2.firebasestorage.app',
    measurementId: 'G-LQYXXJ2BDP',
  );
}
